FROM alpine:latest

WORKDIR /pb

RUN wget https://github.com/pocketbase/pocketbase/releases/download/v0.16.6/pocketbase_0.16.6_linux_amd64.zip \
  && unzip pocketbase_0.16.6_linux_amd64.zip \
  && rm pocketbase_0.16.6_linux_amd64.zip \
  && chmod +x pocketbase

EXPOSE 8090

CMD ["./pocketbase", "serve", "--http=0.0.0.0:8090", "--dir=/pb_data"]