# Dockerfile.poa
FROM python:3.10-slim

# 기본 패키지 설치
RUN apt-get update && apt-get install -y \
  git \
  net-tools \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# 작업 디렉토리 설정
WORKDIR /app

RUN ls /app
COPY ./app/requirements.txt /app/requirements.txt

RUN pip install --upgrade pip && pip install -r /app/requirements.txt

# 애플리케이션 실행
CMD ["python", "run.py", "--port=80"]